icons_launcher:
  image_path: "assets/app_icons/app_icon_main.png"
  platforms:
    android:
      enable: true
      image_path: "assets/app_icons/app_icon_main.png"
      # adaptive_background_color: '#ffffff'
      # adaptive_background_image: "assets/ic_background.png"
      # adaptive_foreground_image: "assets/ic_foreground.png"
      # adaptive_round_image: "assets/ic_logo_round.png"
      # adaptive_monochrome_image: "assets/ic_logo_monochrome.png"
    ios:
      enable: true
      image_path: "assets/app_icons/app_icon_main.png"
    web:
      enable: true
      image_path: "assets/app_icons/app_icon_main.png"
      favicon_path: "assets/app_icons/app_icon_main.png"
    macos:
      enable: true
      image_path: "assets/app_icons/app_icon_main.png"
    windows:
      enable: true
      image_path: "assets/app_icons/app_icon_main.png"
    linux:
      enable: true
      image_path: "assets/app_icons/app_icon_main.png"